"""Self-contained HTML report generator."""

from __future__ import annotations

import html as _html
from datetime import datetime, timezone

from crypto_recon.models.finding import Severity
from crypto_recon.models.report import Report
from crypto_recon.utils.logger import get_logger

logger = get_logger(__name__)

_SEVERITY_BADGE_COLORS: dict[str, str] = {
    Severity.CRITICAL.value: "#dc3545",
    Severity.HIGH.value: "#fd7e14",
    Severity.MEDIUM.value: "#ffc107",
    Severity.LOW.value: "#17a2b8",
    Severity.INFO.value: "#6c757d",
}

_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'Segoe UI', Arial, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }
header { background: linear-gradient(135deg, #161b22 0%, #21262d 100%); padding: 2rem; border-bottom: 1px solid #30363d; }
header h1 { color: #58a6ff; font-size: 2rem; }
header p { color: #8b949e; margin-top: 0.25rem; }
.container { max-width: 1200px; margin: 0 auto; padding: 2rem 1rem; }
.summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
.summary-card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1rem; text-align: center; }
.summary-card .count { font-size: 2rem; font-weight: bold; }
.summary-card .label { font-size: 0.85rem; color: #8b949e; text-transform: uppercase; }
.badge { display: inline-block; padding: 0.2em 0.6em; border-radius: 4px; font-size: 0.75rem; font-weight: bold; color: #fff; text-transform: uppercase; }
.findings-section h2 { color: #58a6ff; margin-bottom: 1rem; font-size: 1.4rem; }
details { background: #161b22; border: 1px solid #30363d; border-radius: 6px; margin-bottom: 0.75rem; }
details summary { padding: 0.85rem 1rem; cursor: pointer; display: flex; align-items: center; gap: 0.75rem; user-select: none; }
details summary:hover { background: #1c2128; }
details summary .title { flex: 1; font-weight: 500; }
details summary .category { font-size: 0.8rem; color: #8b949e; margin-left: auto; padding-right: 1rem; }
.finding-body { padding: 1rem 1.25rem; border-top: 1px solid #30363d; }
.finding-body table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
.finding-body td { padding: 0.4rem 0.6rem; vertical-align: top; }
.finding-body td:first-child { color: #8b949e; width: 140px; font-weight: 500; }
.finding-body tr + tr td { border-top: 1px solid #21262d; }
code { background: #21262d; padding: 0.15em 0.4em; border-radius: 3px; font-size: 0.85em; word-break: break-all; }
footer { text-align: center; padding: 1.5rem; color: #484f58; font-size: 0.85rem; border-top: 1px solid #21262d; margin-top: 2rem; }
"""


class HTMLOutput:
    """Generate a professional, self-contained HTML report."""

    def write(self, report: Report, filepath: str) -> None:
        """Write the HTML report to *filepath*.

        Args:
            report: Report to render.
            filepath: Destination file path.
        """
        content = self.generate(report)
        try:
            with open(filepath, "w", encoding="utf-8") as fh:
                fh.write(content)
            logger.info("HTML report saved to %s", filepath)
        except OSError as exc:
            logger.error("Failed to write HTML report to %s: %s", filepath, exc)

    def generate(self, report: Report) -> str:
        """Render the full HTML report string.

        Args:
            report: Report to render.

        Returns:
            Complete HTML document as a string.
        """
        summary = report.summary()
        by_sev = summary["by_severity"]
        generated_at = (report.end_time or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M:%S UTC")

        summary_cards = self._summary_cards(by_sev, summary["total_findings"], summary["total_assets"])
        assets_html = self._assets_html(report)
        findings_html = self._findings_html(report)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CryptoRecon Report – {_html.escape(report.target)}</title>
<style>{_CSS}</style>
</head>
<body>
<header>
  <h1>🔐 CryptoRecon Security Report</h1>
  <p>Target: <strong>{_html.escape(report.target)}</strong> &nbsp;|&nbsp;
     Scan Type: <strong>{_html.escape(report.scan_type)}</strong> &nbsp;|&nbsp;
     Generated: {generated_at}</p>
</header>
<div class="container">
  <div class="summary-grid">
    {summary_cards}
  </div>
  <div class="findings-section">
    <h2>CBOM Assets</h2>
    {assets_html}
  </div>
  <div class="findings-section">
    <h2>Detailed Findings</h2>
    {findings_html}
  </div>
</div>
  <footer>Generated by CryptoRecon v2.1 &mdash; For authorised security testing only.</footer>
</body>
</html>"""

    # ------------------------------------------------------------------ helpers

    def _summary_cards(self, by_sev: dict, total: int, total_assets: int) -> str:
        cards = [
            f'<div class="summary-card"><div class="count" style="color:#58a6ff">{total}</div>'
            f'<div class="label">Total</div></div>'
        ]
        cards.append(
            f'<div class="summary-card"><div class="count" style="color:#9fef00">{total_assets}</div>'
            f'<div class="label">Assets</div></div>'
        )
        for sev in Severity:
            count = by_sev.get(sev.value, 0)
            color = _SEVERITY_BADGE_COLORS[sev.value]
            cards.append(
                f'<div class="summary-card">'
                f'<div class="count" style="color:{color}">{count}</div>'
                f'<div class="label">{sev.value}</div></div>'
            )
        return "\n    ".join(cards)

    def _findings_html(self, report: Report) -> str:
        if not report.findings:
            return '<p style="color:#8b949e;">No findings recorded.</p>'

        sorted_findings = sorted(
            report.findings,
            key=lambda f: list(Severity).index(f.severity),
        )

        parts: list[str] = []
        for finding in sorted_findings:
            sev_val = finding.severity.value
            badge_color = _SEVERITY_BADGE_COLORS[sev_val]
            badge = f'<span class="badge" style="background:{badge_color}">{sev_val}</span>'

            rows = []
            evidence_summary = finding.evidence.summary() if finding.evidence else ""
            for label, value in [
                ("Description", finding.description),
                ("Category", finding.category.value),
                ("Confidence", finding.confidence.value),
                ("Evidence", evidence_summary),
                ("Remediation", finding.remediation),
                ("CWE", finding.cwe),
                ("CVE", finding.cve),
                ("URL", f'<a href="{_html.escape(finding.url)}" style="color:#58a6ff">{_html.escape(finding.url)}</a>' if finding.url else ""),
            ]:
                if value:
                    rows.append(
                        f"<tr><td>{_html.escape(label)}</td>"
                        f"<td><code>{_html.escape(str(value)) if label not in ('URL',) else value}</code></td></tr>"
                    )

            parts.append(
                f"<details>\n"
                f"  <summary>{badge} <span class='title'>{_html.escape(finding.title)}</span>"
                f"  <span class='category'>{_html.escape(finding.category.value)}</span></summary>\n"
                f"  <div class='finding-body'><table>{''.join(rows)}</table></div>\n"
                f"</details>"
            )

        return "\n".join(parts)

    def _assets_html(self, report: Report) -> str:
        if not report.assets:
            return '<p style="color:#8b949e;">No assets recorded.</p>'

        rows: list[str] = []
        for asset in sorted(report.assets, key=lambda a: a.asset_type.value):
            rows.append(
                "<tr>"
                f"<td>{_html.escape(asset.asset_type.value)}</td>"
                f"<td>{_html.escape(asset.name)}</td>"
                f"<td><code>{_html.escape(asset.evidence.summary() if asset.evidence else '')}</code></td>"
                f"<td>{_html.escape(asset.confidence.value)}</td>"
                "</tr>"
            )

        return (
            "<div class='finding-body'><table>"
            "<tr><td>Type</td><td>Name</td><td>Evidence</td><td>Confidence</td></tr>"
            f"{''.join(rows)}</table></div>"
        )
